repos:
- repo: local
  hooks:
    - id: check-secrets-file-exists
      name: Secret file should exist
      entry: bash -c "if test -f ./secrets/secrets.toml.agebox; then exit 0; else exit 1; fi"
      language: system
    - id: clean-secrets-base-is-empty
      name: Base secrets.toml should be empty
      entry: bash -c "if test -s ./secrets/secrets.toml; then exit 1; else exit 0; fi"
      language: system